name: Building cloud-images
on: 
  workflow_dispatch:

jobs:
  building-x86-container:
    runs-on: alt-sisyphus
    steps:
      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/builder.key
          chmod 600 ~/.ssh/builder.key
          cat >>~/.ssh/config <<END
          Host builder
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/builder.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.BUILDER_SSH_USER }}
          SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
          SSH_HOST: ${{ secrets.BUILDER_SSH_HOST }}
      - name: Update building script from git
        run: |
          ssh builder 'cd cloud-build && git fetch origin && git pull -f origin configs --rebase'          
      - name: Run script for containers on x86
        run: |
          ssh builder 'cd cloud-build && ./cloud-build.py -c ./configs/cb-ve-x86.yaml \
          --stages build test sync --create-remote-dirs'

  building-other-container:
    runs-on: alt-sisyphus
    if: ${{ always() }}
    needs: building-x86-container
    steps:
      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/builder.key
          chmod 600 ~/.ssh/builder.key
          cat >>~/.ssh/config <<END
          Host builder
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/builder.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.BUILDER_SSH_USER }}
          SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
          SSH_HOST: ${{ secrets.BUILDER_SSH_HOST }}
      - name: Update building script from git
        run: |
          ssh builder 'cd cloud-build && git fetch origin && git pull -f origin configs --rebase'          
      - name: Run script for containers on other arches
        run: |
          ssh builder 'cd cloud-build && ./cloud-build.py -c ./configs/cb-ve-other.yaml \
          --stages build test sync --create-remote-dirs'

  building-x86-vm:
    runs-on: alt-sisyphus
    if: ${{ always() }}
    needs: [building-x86-container, building-other-container] 
    steps:
      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/builder.key
          chmod 600 ~/.ssh/builder.key
          cat >>~/.ssh/config <<END
          Host builder
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/builder.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.BUILDER_SSH_USER }}
          SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
          SSH_HOST: ${{ secrets.BUILDER_SSH_HOST }}
      - name: Update building script from git
        run: |
          ssh builder 'cd cloud-build && git fetch origin && git pull -f origin configs --rebase'
      - name: Run script for vm x86
        run: |                                        
          ssh builder 'cd cloud-build && ./cloud-build.py -c ./configs/cb-vm.yaml \
           --stages build test sync --create-remote-dirs'                                                   

  building-aarch:
    runs-on: alt-sisyphus
    steps:
      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/builder.key
          chmod 600 ~/.ssh/builder.key
          cat >>~/.ssh/config <<END
          Host abuilder
            HostName $SSH_T_HOST
            User $SSH_T_USER
            IdentityFile ~/.ssh/builder.key 
            IdentitiesOnly yes
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
          SSH_T_USER: ${{ secrets.TAISHAN_SSH_USER }}
          SSH_T_HOST: ${{ secrets.TAISHAN_SSH_HOST }}
      - name: Update building script from git                                          
        run: |                                                                         
          ssh -A abuilder "ssh builder 'cd cloud-build && git fetch origin && git pull -f origin configs --rebase'"
      - name: Run script for container on aarch
        run: |
          ssh -A abuilder "ssh builder 'cd cloud-build && ./cloud-build.py -c ./configs/cb-ve-aarch64.yaml --stages build test sync --create-remote-dirs'"
      - name: Run script for vm aarch
        run: |
          ssh -A abuilder "ssh builder 'cd cloud-build && ./cloud-build.py -c ./configs/cb-vm-aarch64.yaml --stages build sync --create-remote-dirs'"

  testing-aarch-vm:
    runs-on: alt-sisyphus
    if: ${{ always() }}
    needs: [building-aarch]
    steps:
      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/builder.key
          chmod 600 ~/.ssh/builder.key
          cat >>~/.ssh/config <<END
          Host builder
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/builder.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.BUILDER_SSH_USER }}
          SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
          SSH_HOST: ${{ secrets.BUILDER_SSH_HOST }}
      - name: Copy vm-images to .local storage on x86_64-host to run tests
        run: |
          ssh -A builder "for br in 'p10 p11 Sisyphus'; do rsync --progress \
                        --rsh='ssh -i ~/.ssh/builder-x86' \
                        ~/images/$br/aarch64/alt-$br-cloud-aarch64.qcow2 $SSH_T_USER@$SSH_T_HOST:/home/$SSH_T_USER/images/; done"
        env:
          SSH_T_USER: ${{ secrets.TAISHAN_SSH_USER }}
          SSH_T_HOST: ${{ secrets.TAISHAN_SSH_HOST }}
      - name: Run tests
        run: |
          ssh -A builder "ssh -i ~/.ssh/builder-x86 $SSH_T_USER@$SSH_T_HOST '~/test_images/test.sh'"
        env:
          SSH_T_USER: ${{ secrets.TAISHAN_SSH_USER }}
          SSH_T_HOST: ${{ secrets.TAISHAN_SSH_HOST }}


