name: Building base-docker-images
on: 
  workflow_dispatch:
jobs:
  building-docker-base:
    runs-on: alt-sisyphus
    steps:
      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/builder.key
          chmod 600 ~/.ssh/builder.key
          cat >>~/.ssh/config <<END
          Host abuilder
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/builder.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.TAISHAN_SSH_USER }}
          SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
          SSH_HOST: ${{ secrets.TAISHAN_SSH_HOST }}
      - name: Podman login
        run: |
          ssh -A abuilder ssh builder-x86 "podman login --username $P_USER --password $P_PASS ${{ vars.IMAGES_REPO }}"
        env:
          P_USER: ${{ secrets.PODMAN_USER }}
          P_PASS: ${{ secrets.PODMAN_PASS }}
      - name: Run building base docker images
        run: |
          ssh -A abuilder "ssh builder-x86 'cd base-image-forge && ./build.py --use-local-source -b p10 p11 Sisyphus'"
        
