name: Building base-docker-images
on: 
  workflow_dispatch:
env:
  REPO: altlinux.space
jobs:
  building-docker-base:
    runs-on: alt-sisyphus
    steps:
      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/builder.key
          chmod 600 ~/.ssh/builder.key
          cat >>~/.ssh/config <<END
          Host abuilder
            HostName $SSH_T_HOST
            User $SSH_T_USER
            IdentityFile ~/.ssh/builder.key
            IdentitiesOnly yes
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
          SSH_T_USER: ${{ secrets.TAISHAN_SSH_USER }}
          SSH_T_HOST: ${{ secrets.TAISHAN_SSH_HOST }}
      - name: Run building base docker images
        run: |
          ssh abuilder ssh builder-x86 "podman login --username $P_USER --password $P_PASS ${{ env.REPO }}"
          ssh abuilder "ssh builder-x86 'cd base-image-forge && ./build.py -b p10 p11 Sisyphus'"
        env:
          P_USER: ${{ secrets.PODMAN_USER }}
          P_PASS: ${{ secrets.PODMAN_PASS }}
