name: Signing cloud-images
on: 
  workflow_dispatch:

jobs:
  building:
    runs-on: alt-sisyphus
    steps:
      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/builder.key
          chmod 600 ~/.ssh/builder.key
          echo "SSH_USER=$SSH_USER, SSH_HOST=$SSH_HOST, SSH_TAISHAN_USER=$SSH_T_USER, SSH_TAISHAN_HOST=$SSH_T_HOST, SSH_TAISHAN_PORT=$SSH_T_PORT"
          #> ~/.ssh/known_hosts #SSH_KH: ${{ secrets.BUILDER_SSH_KH }}
          cat >>~/.ssh/config <<END
          Host builder
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/builder.key
            StrictHostKeyChecking no
          Host taishan
            HostName $SSH_T_HOST
            User $SSH_T_USER
            Port $SSH_T_PORT
            IdentityFile ~/.ssh/builder.key 
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.BUILDER_SSH_USER }}
          SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
          SSH_HOST: ${{ secrets.BUILDER_SSH_HOST }}
          SSH_T_USER: ${{ secrets.TAISHAN_SSH_USER }}
          SSH_T_PORT: ${{ secrets.TAISHAN_SSH_PORT }}
          SSH_T_HOST: ${{ secrets.TAISHAN_SSH_HOST }}
      - name: Display Python version
        run: ssh builder 'python3 --version'
      - name: Check script folder
        run: |
          ssh builder 'ls -a cloud-build/'
      - name: Update building script from git
        run: |
          ssh builder 'cd cloud-build && git pull -f origin configs --rebase'                    
      - name: Run sign script
        run: |
          ssh builder 'cd cloud-build && ./cloud-build.py --built-images-dir ~/images --stages copy_external_files sign sync -c ~/sign-config/master.yaml'                    
      - name: Check scripts result for x86
        run: |
          ssh builder 'ls -a proto/Sisyphus/cloud/x86_64/' 
