name: Signing cloud-images
on:
  workflow_dispatch:

jobs:
  building:
    runs-on: als-huge
    container:
      image: registry.altlinux.org/sisyphus/node:latest
    steps:
      - name: Configure ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/builder.key
          chmod 600 ~/.ssh/builder.key
          #> ~/.ssh/known_hosts #SSH_KH: ${{ secrets.BUILDER_SSH_KH }}
          cat >>~/.ssh/config <<END
          Host abuilder
            HostName $SSH_T_HOST
            User $SSH_T_USER
            IdentityFile ~/.ssh/builder.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
          SSH_T_USER: ${{ secrets.TAISHAN_SSH_USER }}
          SSH_T_HOST: ${{ secrets.TAISHAN_SSH_HOST }}
      - name: Update building script from git
        run: |
          ssh -A abuilder "ssh builder-x86 'cd cloud-build && git pull -f origin configs --rebase'"
      - name: Run sign script
        run: |
          ssh -A abuilder "ssh builder-x86 'cd cloud-build && ./cloud-build.py --built-images-dir ~/images --stages copy_external_files sign sync -c ~/sign-config/master.yaml'"
