---
remote: 'cloud@master:/home/cloud/images/{branch}/{arch}'
repository_url: http://ftp.altlinux.org/pub/distributions/ALTLinux/{branch}/branch
try_build_all: True
log_level: debug

rebuild_after:
  days: 5

images:
  rootfs-minimal:
    target: ve/docker
    kinds:
    - tar.xz
    tests:
    - method: docker
  rootfs-systemd:
    target: ve/systemd-networkd
    kinds:
    - tar.xz
    tests:
    - method: lxd
    scripts:
    - securetty
    - netsharedpath
  rootfs-systemd-etcnet:
    target: ve/systemd-etcnet
    kinds:
    - tar.xz
    tests:
    - method: lxd
    scripts:
    - securetty
    - netsharedpath
  rootfs-sysvinit:
    target: ve/sysvinit-etcnet
    kinds:
    - tar.xz
    tests:
    - method: lxd
    scripts:
    - securetty
    - netsharedpath
  cloud:
    target: vm/cloud-systemd
    kinds:
    - qcow2c
    rename:
      regex: '(.*)\.qcow2c$'
      to: '\1.qcow2'
    scripts:
    - grub_install
  # workstation-cloud:
    # target: vm/alt-workstation-cloud
    # branding: 'none'
    # kinds:
    # - qcow2c
    # exclude_branches:
    # - Sisyphus
    # - p9
    # - p8
    # - c8
    # rename:
      # regex: '(.*)\.qcow2c$'
      # to: '\1.qcow2'
    # scripts:
    # - grub_install

branches:
  Sisyphus:
    arches:
      aarch64:
    repository_url: http://ftp.altlinux.org/pub/distributions/ALTLinux/{branch}
  p10:
    arches:
      aarch64:
    branding: alt-starterkit
  p9:
    arches:
      aarch64:
    branding: alt-starterkit

scripts:
  grub_install:
    contents: |
      #!/bin/sh

      mkdir -p /etc/firsttime.d
      touch /etc/firsttime.d/grub-install
      chmod +x /etc/firsttime.d/grub-install
      echo '#!/bin/sh -eu'  >> /etc/firsttime.d/grub-install
      echo >> /etc/firsttime.d/grub-install
      echo grub-install  >> /etc/firsttime.d/grub-install
    global: no
    number: 80
  securetty:
    contents: |
      #!/bin/sh

      echo pts/0 >> /etc/securetty
      echo pts/1 >> /etc/securetty
    global: no
    number: 1
  netsharedpath:
    contents: |
      #!/bin/sh

      echo %_netsharedpath /sys:/proc > /etc/rpm/macros.d/container
    global: no
    number: 20
  apt_sources:
    contents: |
      #!/bin/sh

      repo_source=/etc/apt/sources.list.d/altsp.list
      [ -s "$repo_source" ] || exit 0
      sed -i -E 's/^\s*#(rpm.*http)/\1/' "$repo_source"
    global: no
    number: 80
...
