---
remote: 'cloud@172.16.0.2:/home/cloud/images/{branch}/{arch}'
repository_url: copy:///space/ALT/{branch}
try_build_all: True
log_level: debug

rebuild_after:
  days: 5

images:
  rootfs-minimal:
    target: ve/docker
    kinds:
    - tar.xz
    tests:
    - method: docker
  rootfs-systemd:
    target: ve/systemd-networkd
    kinds:
    - tar.xz
    tests:
    - method: lxd
    scripts:
    - securetty
  rootfs-systemd-etcnet:
    target: ve/systemd-etcnet
    kinds:
    - tar.xz
    tests:
    - method: lxd
    scripts:
    - securetty
  rootfs-sysvinit:
    target: ve/sysvinit-etcnet
    kinds:
    - tar.xz
    tests:
    - method: lxd
    scripts:
    - securetty
    exclude_branches:
    - c8

branches:
  Sisyphus:
    arches:
      i586:
      x86_64:
  p10:
    arches:
      i586:
      x86_64:
    branding: alt-starterkit
  p9:
    arches:
      i586:
      x86_64:
    branding: alt-starterkit

scripts:
  securetty:
    contents: |
      #!/bin/sh

      echo pts/0 >> /etc/securetty
      echo pts/1 >> /etc/securetty
      echo console >> /etc/securetty
    global: no
    number: 1
  apt_sources:
    contents: |
      #!/bin/sh

      repo_source=/etc/apt/sources.list.d/altsp.list
      [ -s "$repo_source" ] || exit 0
      sed -i -E 's/^\s*#(rpm.*http)/\1/' "$repo_source"
    global: no
    number: 80
...
