---
remote: 'cloud@172.16.0.2:/home/cloud/images/{branch}/{arch}'
repository_url: copy:///space/ALT/{branch}
try_build_all: True
log_level: debug

rebuild_after:
  days: 5

images:
  rootfs-minimal:
    target: ve/docker
    kinds:
    - tar.xz
    tests:
    - method: docker
  rootfs-systemd:
    target: ve/systemd-networkd
    kinds:
    - tar.xz
    tests:
    - method: lxd
    scripts:
    - securetty
    - machine_id
    packages:
    - apt-scripts
    - systemd-settings-disable-kill-user-processes
  rootfs-systemd-etcnet:
    target: ve/systemd-etcnet
    kinds:
    - tar.xz
    tests:
    - method: lxd
    scripts:
    - securetty
    - machine_id
  rootfs-sysvinit:
    target: ve/sysvinit-etcnet
    kinds:
    - tar.xz
    tests:
    - method: lxd
    scripts:
    - securetty
    exclude_branches:
    - c8

branches:
  Sisyphus:
    arches:
      ppc64le:
      armh:
  p10:
    arches:
      ppc64le:
      armh:
    branding: alt-starterkit
  p9:
    arches:
      ppc64le:
      armh:
    branding: alt-starterkit

scripts:
  machine_id:
    contents: |
      #!/bin/sh -exu

      etc_machine_id=/etc/machine-id
      dbus_machine_id=/var/lib/dbus/machine-id

      rm -f "$etc_machine_id" "$dbus_machine_id"
      touch "$etc_machine_id"
    global: no
    number: 90
  securetty:
    contents: |
      #!/bin/sh

      echo pts/0 >> /etc/securetty
      echo pts/1 >> /etc/securetty
      echo console >> /etc/securetty
    global: no
    number: 1
  apt_sources:
    contents: |
      #!/bin/sh

      repo_source=/etc/apt/sources.list.d/altsp.list
      [ -s "$repo_source" ] || exit 0
      sed -i -E 's/^\s*#(rpm.*http)/\1/' "$repo_source"
    global: no
    number: 80
...
