---
remote: '/home/builder/images/{branch}/{arch}'
repository_url: http://ftp.altlinux.org/pub/distributions/ALTLinux/ports/{arch}
try_build_all: True
log_level: debug

rebuild_after:
  days: 5

images:
  rootfs-minimal:
    target: ve/docker
    kinds:
    - tar.xz
    tests:
    - method: docker
  rootfs-systemd:
    target: ve/systemd-networkd
    kinds:
    - tar.xz
    #tests:
    #- method: lxd
    scripts:
    - securetty
    - netsharedpath
  rootfs-systemd-etcnet:
    target: ve/systemd-etcnet
    kinds:
    - tar.xz
    #tests:
    #- method: lxd
    scripts:
    - securetty
    - netsharedpath
  rootfs-sysvinit:
    target: ve/sysvinit-etcnet
    kinds:
    - tar.xz
    #tests:
    #- method: lxd
    scripts:
    - securetty
    - netsharedpath

branches:
  Sisyphus:
    arches:
      loongarch64:
      riscv64:
  p11:
    arches:
      loongarch64:
    branding: alt-container

scripts:
  securetty:
    contents: |
      #!/bin/sh

      echo pts/0 >> /etc/securetty
      echo pts/1 >> /etc/securetty
      echo console >> /etc/securetty
    global: no
    number: 1
  netsharedpath:
    contents: |
      #!/bin/sh

      echo %_netsharedpath /sys:/proc > /etc/rpm/macros.d/container
    global: no
    number: 20
  apt_sources:
    contents: |
      #!/bin/sh

      repo_source=/etc/apt/sources.list.d/altsp.list
      [ -s "$repo_source" ] || exit 0
      sed -i -E 's/^\s*#(rpm.*http)/\1/' "$repo_source"
    global: no
    number: 80
...
