---
remote: 'cloud@172.16.0.2:/home/cloud/images/{branch}/{arch}'
repository_url: copy:///space/ALT/{branch}
try_build_all: True
log_level: debug

rebuild_after:
  days: 5

images:
  opennebula:
    target: vm/opennebula-systemd
    kinds:
    - qcow2c
    exclude_arches:
    - aarch64
    - armh
    - ppc64le
    exclude_branches:
    - c8
    scripts:
    - machine_id
    rename:
      regex: '(.*)\.qcow2c$'
      to: '\1.qcow2'
  cloud:
    target: vm/cloud-systemd
    kinds:
    - qcow2c
    exclude_arches:
    - aarch64
    - armh
    - ppc64le
    exclude_branches:
    - p8
    - c8
    scripts:
    - machine_id
    tests:
    - method: prog(cloud-build-test-cloud)
    rename:
      regex: '(.*)\.qcow2c$'
      to: '\1.qcow2'

branches:
  Sisyphus:
    arches:
      i586:
      x86_64:
      # aarch64:
      # ppc64le:
      # armh:
  p10:
    arches:
      i586:
      x86_64:
      # aarch64:
      # ppc64le:
      # armh:
    branding: alt-starterkit
  p9:
    arches:
      i586:
      x86_64:
      # aarch64:
      # ppc64le:
      # armh:
    branding: alt-starterkit

scripts:
  machine_id:
    contents: |
      #!/bin/sh -exu

      etc_machine_id=/etc/machine-id
      dbus_machine_id=/var/lib/dbus/machine-id

      rm -f "$etc_machine_id" "$dbus_machine_id"
      touch "$etc_machine_id"
    global: no
    number: 90
  securetty:
    contents: |
      #!/bin/sh

      echo pts/0 >> /etc/securetty
      echo pts/1 >> /etc/securetty
    global: no
    number: 1
  apt_sources:
    contents: |
      #!/bin/sh

      repo_source=/etc/apt/sources.list.d/altsp.list
      [ -s "$repo_source" ] || exit 0
      sed -i -E 's/^\s*#(rpm.*http)/\1/' "$repo_source"
    global: no
    number: 80
...
