---
remote: '/home/builder/images/{branch}/{arch}'
repository_url: copy:///space/ALT/{branch}
try_build_all: True
log_level: debug

rebuild_after:
  days: 5

images:
  rootfs-minimal:
    target: ve/docker
    kinds:
    - tar.xz
    tests:
    - method: docker

branches:
  Sisyphus:
    arches:
      i586:
      x86_64:
  p10:
    arches:
      i586:
      x86_64:
    branding: alt-container
  p11:
    arches:
      i586:
      x86_64:
    branding: alt-container

...
