---
remote: 'builder@cloud-builder.office.basealt.ru:/home/builder/images/{branch}/{arch}'
repository_url: http://mirror.yandex.ru/altlinux/{branch}/branch
try_build_all: True
log_level: debug

rebuild_after:
  days: 5

images:
  rootfs-minimal:
    target: ve/docker
    kinds:
    - tar.xz
    tests:
    - method: docker

branches:
  Sisyphus:
    arches:
      aarch64:
    repository_url: http://ftp.altlinux.org/pub/distributions/ALTLinux/{branch}
  p10:
    arches:
      aarch64:
    branding: alt-container
  p11:
    arches:
      aarch64:
    branding: alt-container

...
