---
remote: '/home/builder/proto/{branch}/cloud/{arch}'
key: 0x17F112840DE94827C9C109FD3E2B30EA57EF33CE
repository_url: http://mirror.yandex.ru/altlinux/{branch}/branch
try_build_all: True
log_level: debug

external_files: '~/external-files'

rebuild_after:
  days: 99999

images:
  rootfs-minimal:
    target: ve/docker
    kinds:
    - tar.xz
  rootfs-systemd:
    target: ve/systemd-networkd
    kinds:
    - tar.xz
  rootfs-systemd-etcnet:
    target: ve/systemd-etcnet
    kinds:
    - tar.xz
  rootfs-sysvinit:
    target: ve/sysvinit-etcnet
    kinds:
    - tar.xz
    exclude_branches:
    - c8
  opennebula:
    target: vm/opennebula-systemd
    kinds:
    - qcow2
    exclude_arches:
    - armh
    - ppc64le
    - i586
    exclude_branches:
    - c8
  cloud:
    target: vm/cloud-systemd
    kinds:
    - qcow2
    exclude_arches:
    - armh
    - ppc64le
    - i586
    exclude_branches:
    - c8
  workstation-cloud:
    target: vm/alt-workstation-cloud
    kinds:
    - qcow2c
    exclude_arches:
    - armh
    - ppc64le
    - i586
    exclude_branches:
    - p8
    - c8
    # rename:
      # regex: '(.*)\.qcow2c$'
      # to: '\1.qcow2'

branches:
  p11:
    arches:
      i586:
      x86_64:
      aarch64:
...
